version: 2.1

executors:
  default:
    parameters:
      api-version:
        description: The Android API version to use.
        type: string
        default: "28"
    docker:
      - image: circleci/android:api-<<parameters.api-version>>
        environment:
          # kotlin.incremental=false and kotlin.compiler.execution.strategy=in-process are required due to an issue with the Kotlin compiler in
          # memory constrained environments: https://youtrack.jetbrains.com/issue/KT-15562
          GRADLE_OPTS: -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

commands:
  generate-gradle-checksums:
    steps:
      - run:
          name: Generate Gradle checksums
          command: |
            find . -mindepth 2 -name "*.gradle.kts" -type f | sort | xargs shasum > gradle-checksums.txt
            cat gradle-checksums.txt

  restore-gradle-cache:
    description: Restore the cache of ~/.gradle based on the local build files.
    parameters:
      cache-prefix:
        type: string
        default: gradle-{{ .Environment.CIRCLE_JOB }}
    steps:
      - generate-gradle-checksums
      - restore_cache:
          keys:
            - <<parameters.cache-prefix>>-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle-checksums.txt" }}
            - <<parameters.cache-prefix>>-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-
            - <<parameters.cache-prefix>>-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-

  save-gradle-cache:
    description: Cache the contents of ~/.gradle based on the local build files.
    parameters:
      cache-prefix:
        type: string
        default: gradle-{{ .Environment.CIRCLE_JOB }}
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: <<parameters.cache-prefix>>-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle-checksums.txt" }}

  lint:
    description: Run lint

    steps:
      - run:
          name: Lint
          command: ./gradlew lintKotlin

workflows:
  version: 2

  build:
    jobs:
      - generate-gradle-checksums:
