version: 2

android_env: &android_env
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    JVM_OPTS: -Xmx3200m
    GRADLE_OPTS: -Xmx3200m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

references:
  restore_gradle: &restore_gradle
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
        - v1-dependencies-

  save_gradle: &save_gradle
    save_cache:
      key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      paths:
        - ~/.gradle

jobs:
  build:
    <<: *android_env
    steps:
      - checkout

      - *restore_gradle

      - run: ./gradlew dependencies

      - *save_gradle

      - run: ./gradlew lintKotlin

      - run: ./gradlew test

      - run: bash <(curl -s https://codecov.io/bash)

  deploy:
    <<: *android_env
    steps:
      - checkout

      - *restore_gradle

      - run: ./gradlew dependencies

      - *save_gradle

      - run: ./gradlew clean build bintrayUpload -PBINTRAY_USER=$BINTRAY_USER -PBINTRAY_KEY=$BINTRAY_KEY -PdryRun=false -Ppublish=true

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
